from schemas.schema import PerformanceIncentive, InputFindPerformanceIncentive
PERFORMANCE_INCENTIVE = [
    {
        "type": "SP",
        "min_sales_point": 5,
        "max_sales_point": 9,
        "min_active_person": 0,
        "max_active_person": 0,
        "incentive": 500000,
    },
    {
        "type": "SP",
        "min_sales_point": 10,
        "max_sales_point": 19,
        "min_active_person": 0,
        "max_active_person": 0,
        "incentive": 1500000,
    },
    {
        "type": "SP",
        "min_sales_point": 20,
        "max_sales_point": 29,
        "min_active_person": 0,
        "max_active_person": 0,
        "incentive": 2000000,
    },
    {
       "type": "SP",
        "min_sales_point": 30,
        "max_sales_point": 9999999,
        "min_active_person": 0,
        "max_active_person": 0,
        "incentive": 3000000,
    },
    {
        "type": "SM",
        "min_sales_point": 2,
        "max_sales_point": 4,
        "min_active_person": 5,
        "max_active_person": 9,
        "incentive": 100000,
    },
    {
        "type": "SM",
        "min_sales_point": 5,
        "max_sales_point": 9,
        "min_active_person": 5,
        "max_active_person": 9,
        "incentive": 100000,
    },
    {
        "type": "SM",
        "min_sales_point": 10,
        "max_sales_point": 14,
        "min_active_person": 5,
        "max_active_person": 9,
        "incentive": 100000,
    },
    {
        "type": "SM",
        "min_sales_point": 15,
        "max_sales_point": 19,
        "min_active_person": 5,
        "max_active_person": 9,
        "incentive": 100000,
    },
    {
        "type": "SM",
        "min_sales_point": 20,
        "max_sales_point": 9999999,
        "min_active_person": 5,
        "max_active_person": 9,
        "incentive": 100000,
    },
    {
        "type": "SM",
        "min_sales_point": 2,
        "max_sales_point": 4,
        "min_active_person": 10,
        "max_active_person": 14,
        "incentive": 100000,
    },
    {
        "type": "SM",
        "min_sales_point": 5,
        "max_sales_point": 9,
        "min_active_person": 10,
        "max_active_person": 14,
        "incentive": 200000,
    },
    {
        "type": "SM",
        "min_sales_point": 10,
        "max_sales_point": 14,
        "min_active_person": 10,
        "max_active_person": 14,
        "incentive": 200000,
    },
    {
        "type": "SM",
        "min_sales_point": 15,
        "max_sales_point": 19,
        "min_active_person": 10,
        "max_active_person": 14,
        "incentive": 200000,
    },
    {
        "type": "SM",
        "min_sales_point": 20,
        "max_sales_point": 9999999,
        "min_active_person": 10,
        "max_active_person": 14,
        "incentive": 200000,
    },
    {
        "type": "SM",
        "min_sales_point": 2,
        "max_sales_point": 4,
        "min_active_person": 15,
        "max_active_person": 19,
        "incentive": 100000,
    },
    {
        "type": "SM",
        "min_sales_point": 5,
        "max_sales_point": 9,
        "min_active_person": 15,
        "max_active_person": 19,
        "incentive": 200000,
    },
    {
        "type": "SM",
        "min_sales_point": 10,
        "max_sales_point": 14,
        "min_active_person": 15,
        "max_active_person": 19,
        "incentive": 500000,
    },
    {
        "type": "SM",
        "min_sales_point": 15,
        "max_sales_point": 19,
        "min_active_person": 15,
        "max_active_person": 19,
        "incentive": 500000,
    },
    {
        "type": "SM",
        "min_sales_point": 20,
        "max_sales_point": 9999999,
        "min_active_person": 15,
        "max_active_person": 19,
        "incentive": 500000,
    },
    {
        "type": "SM",
        "min_sales_point": 2,
        "max_sales_point": 4,
        "min_active_person": 20,
        "max_active_person": 9999999,
        "incentive": 100000,
    },
    {
        "type": "SM",
        "min_sales_point": 5,
        "max_sales_point": 9,
        "min_active_person": 20,
        "max_active_person": 9999999,
        "incentive": 200000,
    },
    {
        "type": "SM",
        "min_sales_point": 10,
        "max_sales_point": 14,
        "min_active_person": 20,
        "max_active_person": 9999999,
        "incentive": 500000,
    },
    {
        "type": "SM",
        "min_sales_point": 15,
        "max_sales_point": 19,
        "min_active_person": 20,
        "max_active_person": 9999999,
        "incentive": 1000000,
    },
    {
        "type": "SM",
        "min_sales_point": 20,
        "max_sales_point": 9999999,
        "min_active_person": 20,
        "max_active_person": 9999999,
        "incentive": 2000000,
    },
    {
        "type": "GM",
        "min_sales_point": 3,
        "max_sales_point": 5,
        "min_active_person": 20,
        "max_active_person": 49,
        "incentive": 300000,
    },
    {
        "type": "GM",
        "min_sales_point": 6,
        "max_sales_point": 8,
        "min_active_person": 20,
        "max_active_person": 49,
        "incentive": 500000,
    },
    {
        "type": "GM",
        "min_sales_point": 9,
        "max_sales_point": 11,
        "min_active_person": 20,
        "max_active_person": 49,
        "incentive": 1000000,
    },
    {
        "type": "GM",
        "min_sales_point": 12,
        "max_sales_point": 14,
        "min_active_person": 20,
        "max_active_person": 49,
        "incentive": 1500000,
    },
    {
        "type": "GM",
        "min_sales_point": 15,
        "max_sales_point": 9999999,
        "min_active_person": 20,
        "max_active_person": 49,
        "incentive": 2000000,
    },
    {
        "type": "GM",
        "min_sales_point": 3,
        "max_sales_point": 5,
        "min_active_person": 50,
        "max_active_person": 74,
        "incentive": 300000,
    },
    {
        "type": "GM",
        "min_sales_point": 6,
        "max_sales_point": 8,
        "min_active_person": 50,
        "max_active_person": 74,
        "incentive": 750000,
    },
    {
        "type": "GM",
        "min_sales_point": 9,
        "max_sales_point": 11,
        "min_active_person": 50,
        "max_active_person": 74,
        "incentive": 1250000,
    },
    {
        "type": "GM",
        "min_sales_point": 12,
        "max_sales_point": 14,
        "min_active_person": 50,
        "max_active_person": 74,
        "incentive": 1750000,
    },
    {
        "type": "GM",
        "min_sales_point": 15,
        "max_sales_point": 9999999,
        "min_active_person": 50,
        "max_active_person": 74,
        "incentive": 3000000,
    },
    {
        "type": "GM",
        "min_sales_point": 3,
        "max_sales_point": 5,
        "min_active_person": 75,
        "max_active_person": 99,
        "incentive": 750000,
    },
    {
        "type": "GM",
        "min_sales_point": 6,
        "max_sales_point": 8,
        "min_active_person": 75,
        "max_active_person": 99,
        "incentive": 1000000,
    },
    {
        "type": "GM",
        "min_sales_point": 9,
        "max_sales_point": 11,
        "min_active_person": 75,
        "max_active_person": 99,
        "incentive": 1500000,
    },
    {
        "type": "GM",
        "min_sales_point": 12,
        "max_sales_point": 14,
        "min_active_person": 75,
        "max_active_person": 99,
        "incentive": 2000000,
    },
    {
        "type": "GM",
        "min_sales_point": 15,
        "max_sales_point": 9999999,
        "min_active_person": 75,
        "max_active_person": 99,
        "incentive": 4000000,
    },
    {
        "type": "GM",
        "min_sales_point": 3,
        "max_sales_point": 5,
        "min_active_person": 100,
        "max_active_person": 9999999,
        "incentive": 1500000,
    },
    {
        "type": "GM",
        "min_sales_point": 6,
        "max_sales_point": 8,
        "min_active_person": 100,
        "max_active_person": 9999999,
        "incentive": 2500000,
    },
    {
        "type": "GM",
        "min_sales_point": 9,
        "max_sales_point": 11,
        "min_active_person": 100,
        "max_active_person": 9999999,
        "incentive": 3000000,
    },
    {
        "type": "GM",
        "min_sales_point": 12,
        "max_sales_point": 14,
        "min_active_person": 100,
        "max_active_person": 9999999,
        "incentive": 4000000,
    },
    {
        "type": "GM",
        "min_sales_point": 15,
        "max_sales_point": 9999999,
        "min_active_person": 100,
        "max_active_person": 9999999,
        "incentive": 10000000,
    },
]

def get_by_item(data: InputFindPerformanceIncentive) -> PerformanceIncentive:
    product = next((entry for entry in PERFORMANCE_INCENTIVE if 
                entry["type"] == data.type and
                entry["min_sales_point"] <= data.sales_point and 
                entry["max_sales_point"] >= data.sales_point and
                entry["min_active_person"] <= data.active_person and 
                entry["max_active_person"] >= data.active_person), None)
    if product:
        return PerformanceIncentive(**product)
    else:
        return None